[profile.default]
src = "src"
out = "out"
libs = ["lib"]
broadcast="deployments"
fs_permissions = [{ access = "read-write", path = "./"}]
solc-version = "0.8.20"
optimizer = true
optimizer-runs = 100_000

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
baobab = "https://public-en-kairos.node.kaia.io"
